openapi: 3.0.3
info:
  title: Digital Diary Tauri Commands
  version: 1.0.0
  description: |
    Tauri command contracts for Digital Diary desktop application.
    All commands are invoked from React frontend via `invoke()`.

servers:
  - url: tauri://digital-diary
    description: Tauri IPC bridge (not HTTP, conceptual server)

paths:
  # Time Entries
  /time-entries:
    get:
      summary: Get time entries for a day
      operationId: get_time_entries
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
            example: "2026-01-17"
      responses:
        '200':
          description: List of time entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeEntry'

    post:
      summary: Create a new time entry
      operationId: create_time_entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeEntryInput'
      responses:
        '200':
          description: Created time entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeEntry'

  /time-entries/{id}:
    put:
      summary: Update an existing time entry
      operationId: update_time_entry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeEntryUpdate'
      responses:
        '200':
          description: Updated time entry
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeEntry'

    delete:
      summary: Delete a time entry
      operationId: delete_time_entry
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Time entry deleted

  # Screenshots
  /screenshots/{timestamp}:
    get:
      summary: Get screenshot path for a timestamp
      operationId: get_screenshot_for_time
      parameters:
        - name: timestamp
          in: path
          required: true
          schema:
            type: integer
            description: Unix timestamp in milliseconds
      responses:
        '200':
          description: File path or placeholder
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_path:
                    type: string
                    nullable: true
                  placeholder:
                    type: string
                    example: "No screenshot available"

  # Window Activity
  /window-activity:
    get:
      summary: Get window activity for a time range
      operationId: get_window_activity
      parameters:
        - name: start_time
          in: query
          required: true
          schema:
            type: integer
        - name: end_time
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of window activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WindowActivity'

  # Search
  /search:
    get:
      summary: Search activities by keyword
      operationId: search_activities
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
            minLength: 2
      responses:
        '200':
          description: List of search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResult'

  # Idle Detection
  /idle-periods:
    get:
      summary: Get idle periods for a day
      operationId: get_idle_periods
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of idle periods
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdlePeriod'

    put:
      summary: Resolve an idle period
      operationId: resolve_idle_period
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdlePeriodResolution'
      responses:
        '200':
          description: Idle period resolved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdlePeriod'

  # Export
  /export:
    post:
      summary: Export all data to JSON
      operationId: export_data
      parameters:
        - name: format
          in: query
          required: false
          schema:
            type: string
            enum: [json]
            default: json
      responses:
        '200':
          description: Exported data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportData'

components:
  schemas:
    TimeEntry:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_time:
          type: integer
          description: Unix timestamp (milliseconds)
        end_time:
          type: integer
          description: Unix timestamp (milliseconds)
        label:
          type: string
          maxLength: 500
        color:
          type: string
          nullable: true
          pattern: '^#[0-9A-Fa-f]{6}$'
      required: [id, start_time, end_time, label]

    TimeEntryInput:
      type: object
      properties:
        start_time:
          type: integer
          description: Unix timestamp (milliseconds)
        end_time:
          type: integer
          description: Unix timestamp (milliseconds)
        label:
          type: string
          maxLength: 500
        color:
          type: string
          nullable: true
          pattern: '^#[0-9A-Fa-f]{6}$'
      required: [start_time, end_time, label]

    TimeEntryUpdate:
      type: object
      properties:
        label:
          type: string
          maxLength: 500
        color:
          type: string
          nullable: true
          pattern: '^#[0-9A-Fa-f]{6}$'

    WindowActivity:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        timestamp:
          type: integer
          description: Unix timestamp (milliseconds)
        window_title:
          type: string
          maxLength: 500
        process_name:
          type: string
          maxLength: 255
      required: [id, timestamp, window_title, process_name]

    IdlePeriod:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        start_time:
          type: integer
          description: Unix timestamp (milliseconds)
        end_time:
          type: integer
          description: Unix timestamp (milliseconds)
        resolution:
          type: string
          enum: [discarded, merged, labeled]
          nullable: true
      required: [id, start_time, end_time]

    IdlePeriodResolution:
      type: object
      properties:
        id:
          type: integer
        resolution:
          type: string
          enum: [discarded, merged, labeled]
        target_entry_id:
          type: integer
          nullable: true
          description: Required when resolution is 'merged'
        new_entry_label:
          type: string
          nullable: true
          description: Required when resolution is 'labeled'
      required: [id, resolution]

    SearchResult:
      type: object
      properties:
        type:
          type: string
          enum: [time_entry, window_activity]
        timestamp:
          type: integer
          description: Unix timestamp (milliseconds)
        title:
          type: string
          description: Entry label or window title
        process_name:
          type: string
          nullable: true
      required: [type, timestamp, title]

    ExportData:
      type: object
      properties:
        version:
          type: string
          example: "1.0"
        exported_at:
          type: string
          format: date-time
        time_entries:
          type: array
          items:
            $ref: '#/components/schemas/TimeEntry'
        screenshots:
          type: array
          items:
            type: object
            properties:
              timestamp:
                type: integer
              file_path:
                type: string
        window_activities:
          type: array
          items:
            $ref: '#/components/schemas/WindowActivity'
        idle_periods:
          type: array
          items:
            $ref: '#/components/schemas/IdlePeriod'
      required: [version, exported_at]
